# To get started with security, check out the documentation:

security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 10
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\User
                property: user_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                check_path: login
                login_path: login
                provider: our_db_provider
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
#                default_target_path: after_login_route_name
                #always_use_default_target_path: true
            logout:
                path: logout
                target: login

    access_control:
        - { path ^/(login|register)$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path ^/, role: ROLE_USER }
